data:
  batch_size: 64
  perturbation_file: 'perturbation_neg_master.csv'
  dataset_path: 'data/kitti'
  augmentation: false
model:
  tag: 'resnet18_small_noaug_240906'
  intermediate_1: true
  intermediate_2: false
  epoch_1: 26
  epoch_2: 32
