logging:
  rel_path: 'outputs/logs'
  tag: 'contrastive'
data:
  batch_size: 32
  perturbation_file: 'perturbation_neg_master.csv'
  dataset_path: 'data/kitti'
  augmentation: 'perturbation_pos_master.csv'
meta:
  backbone: 'resnet'
  model_name: 'resnet18_all'
  pretrained_encoder: True
  retrain: False
  pretrained_name: "resnet18_all_aug_240921"
  starting_epoch: "latest"
optimization:
  optimizer: 'adamw'
  epochs: 50
  lr: 1e-3
  weight_decay: 0.05
  margin: 4
  patch_size: 16
  scheduler_step: 30
  scheduler_gamma: 0.1
  mode: 'resnet'
logging_cls:
  rel_path: 'outputs/logs'
  tag: 'classifier'
optimization_cls:
  optimizer: 'adamw'
  epochs: 70
  lr: 1e-3
  weight_decay: 0.05
  scheduler_step: 30
  scheduler_gamma: 0.1
