logging:
  rel_path: 'outputs/logs'
  tag: 'classifier'
data:
  batch_size: 64
  perturbation_file: 'perturbation_neg.csv'
  dataset_path: 'data/kitti'
optimization:
  epochs: 50
  lr: 1e-3
  margin: 4
  scheduler_step: 30
  scheduler_gamma: 0.1