logging:
  rel_path: 'outputs/logs'
  tag: 'contrastive'
data:
  batch_size: 32
  perturbation_file: 'perturbation_neg.csv'
  dataset_path: 'data/kitti_odom'
  augmentation: 'perturbation_pos.csv'
  loader: 'kitti_odom'
meta:
  backbone: 'resnet'
  model_name: 'resnet18_small'
  pretrained_encoder: false
  retrain: false
  pretrained_name: None
  starting_epoch: None
optimization:
  optimizer: 'adamw'
  epochs: 50
  lr: 1e-3
  weight_decay: 0.05
  margin: 4
  patch_size: 16
  scheduler_step: 30
  scheduler_gamma: 0.1
  mode: 'resnet'
logging_cls:
  rel_path: 'outputs/logs'
  tag: 'classifier'
optimization_cls:
  optimizer: 'adamw'
  epochs: 50
  lr: 1e-3
  weight_decay: 0.05
  margin: 4
  scheduler_step: 30
  scheduler_gamma: 0.1
