logging:
  rel_path: 'outputs/logs'
  tag: 'contrastive'
data:
  batch_size: 64
  perturbation_file: 'perturbation_neg_master.csv'
  dataset_path: 'data/kitti'
meta:
  backbone: 'resnet'
  model_name: 'resnet18_small'
optimization:
  epochs: 50
  lr: 1e-4
  weight_decay: 0.05
  margin: 4
  patch_size: 16
  scheduler_step: 30
  scheduler_gamma: 0.1
logging_cls:
  rel_path: 'outputs/logs'
  tag: 'classifier'
optimization_cls:
  epochs: 50
  lr: 1e-4
  margin: 4
  scheduler_step: 30
  scheduler_gamma: 0.1
