logging:
  rel_path: 'outputs/logs'
  tag: 'vit'
data:
  batch_size: 32
  perturbation_file: 'perturbation_neg_master.csv'
  dataset_path: 'data/kitti'
  augmentation: 'perturbation_pos_master.csv'
meta:
  backbone: 'vit'
  model_name: 'vit_small'
  pretrained_encoder: False
  retrain: False
  pretrained_name: None
  starting_epoch: 0
optimization:
  optimizer: 'adamw'
  epochs: 2
  lr: 1e-3
  weight_decay: 0.05
  margin: 4
  patch_size: 16
  scheduler_step: 30
  scheduler_gamma: 0.1
  mode: 'vit'
logging_cls:
  rel_path: 'outputs/logs'
  tag: 'classifier'
optimization_cls:
  optimizer: 'adamw'
  epochs: 2
  lr: 1e-3
  weight_decay: 0.05
  scheduler_step: 30
  scheduler_gamma: 0.1
