logging:
  rel_path: 'outputs/logs'
  tag: 'contrastive'
data:
  batch_size: 64
  perturbation_file: 'perturbation_neg_master.csv'
  dataset_path: 'data/kitti'
optimization:
  epochs: 70
  lr: 1e-3
  margin: 4
  patch_size: 16
  scheduler_step: 10
  scheduler_gamma: 0.2
logging_cls:
  rel_path: 'outputs/logs'
  tag: 'classifier'
optimization_cls:
  epochs: 70
  lr: 1e-3
  margin: 4
  scheduler_step: 30
  scheduler_gamma: 0.1
